# Generated by Django 5.1.1 on 2024-10-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_student_psychologist'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatenote',
            name='sentiment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
