# Generated by Django 5.0.8 on 2024-10-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_privatenote_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cover_photos/'),
        ),
    ]
