# Generated by Django 5.1.1 on 2024-11-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_student_feelings_remove_student_note_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatenote',
            name='recommendation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='privatenote',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='privatenote',
            name='sentiment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
